pipeline {
    agent none
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
    }
    triggers {
        pullRequestFilter(
            branches: [[name: 'feature/**']],
            targets: [[name: 'master']]
        )
    }
    stages {
        stage('Checkout') {
            agent any
            steps {
                checkout scm
            }
        }

        stage('Build and test') {
            parallel {
                stage('Master branch') {
                    when {
                        branch 'master'
                    }
                    agent { label 'master' }
                    steps {
                        sh './gradlew checkstyleMain'
                        sh './gradlew jacocoTestCoverageVerification'
                        sh './gradlew jacocoTestReport'
                        sh './gradlew test'
                    }
                }
                stage('Feature branch') {
                    when {
                        branch 'feature'
                    }
                    agent { label 'master' }
                    steps {
                        sh './gradlew checkstyleMain'
                        sh './gradlew test'
                    }
                }
                stage('Playground branch') {
                    when {
                        branch 'playground'
                    }
                    agent { label 'master' }
                    steps {
                        echo 'Not running tests for playground branch'
                    }
                }
            }
        }

        stage('Build Java Image') {
      container('kaniko') {
        stage('Build a gradle project') {
          sh '''
          echo 'FROM openjdk:8-jre' > Dockerfile
          echo 'COPY ./calculator-0.0.1-SNAPSHOT.jar app.jar' >> Dockerfile
          echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile
          mv /mnt/calculator-0.0.1-SNAPSHOT.jar .
          /kaniko/executor --context `pwd` --destination somonedo/hello-kaniko:1.0
          '''
        }
      }
    }

  }
}
